- action:
  - data:
      button: UP
      entity_id: media_player.lg_webos_tv_43uj6510_sa
    service: webostv.button
  alias: LG Remote UP
  id: lg_homekit_remote_up
  trigger:
  - event_data:
      entity_id: media_player.lg_webos_tv_43uj6510_sa
      key_name: arrow_up
    event_type: homekit_tv_remote_key_pressed
    platform: event
- action:
  - data:
      button: DOWN
      entity_id: media_player.lg_webos_tv_43uj6510_sa
    service: webostv.button
  alias: LG Remote DOWN
  id: lg_homekit_remote_down
  trigger:
  - event_data:
      entity_id: media_player.lg_webos_tv_43uj6510_sa
      key_name: arrow_down
    event_type: homekit_tv_remote_key_pressed
    platform: event
- action:
  - data:
      button: LEFT
      entity_id: media_player.lg_webos_tv_43uj6510_sa
    service: webostv.button
  alias: LG Remote LEFT
  id: lg_homekit_remote_left
  trigger:
  - event_data:
      entity_id: media_player.lg_webos_tv_43uj6510_sa
      key_name: arrow_left
    event_type: homekit_tv_remote_key_pressed
    platform: event
- action:
  - data:
      button: RIGHT
      entity_id: media_player.lg_webos_tv_43uj6510_sa
    service: webostv.button
  alias: LG Remote RIGHT
  id: lg_homekit_remote_right
  trigger:
  - event_data:
      entity_id: media_player.lg_webos_tv_43uj6510_sa
      key_name: arrow_right
    event_type: homekit_tv_remote_key_pressed
    platform: event
- action:
  - data:
      button: ENTER
      entity_id: media_player.lg_webos_tv_43uj6510_sa
    service: webostv.button
  alias: LG Remote SELECT
  id: lg_homekit_remote_select
  trigger:
  - event_data:
      entity_id: media_player.lg_webos_tv_43uj6510_sa
      key_name: select
    event_type: homekit_tv_remote_key_pressed
    platform: event
- action:
  - data:
      button: BACK
      entity_id: media_player.lg_webos_tv_43uj6510_sa
    service: webostv.button
  alias: LG Remote BACK
  id: lg_homekit_remote_back
  trigger:
  - event_data:
      entity_id: media_player.lg_webos_tv_43uj6510_sa
      key_name: back
    event_type: homekit_tv_remote_key_pressed
    platform: event
- action:
  - data:
      button: EXIT
      entity_id: media_player.lg_webos_tv_43uj6510_sa
    service: webostv.button
  alias: LG Remote EXIT
  id: lg_homekit_remote_exit
  trigger:
  - event_data:
      entity_id: media_player.lg_webos_tv_43uj6510_sa
      key_name: exit
    event_type: homekit_tv_remote_key_pressed
    platform: event
- action:
  - data:
      button: HOME
      entity_id: media_player.lg_webos_tv_43uj6510_sa
    service: webostv.button
  alias: LG Remote INFO
  id: lg_homekit_remote_info
  trigger:
  - event_data:
      entity_id: media_player.lg_webos_tv_43uj6510_sa
      key_name: information
    event_type: homekit_tv_remote_key_pressed
    platform: event
